Autonomous integration
GreenMachineReloaded/RelicRecovery pull request #5
Opened 2017-11-28 03:12 UTC by Andor16

I have updated the R1, R2, and B2 programs to handle grabbing a block at the beginning of the game and taking it to one of the cryptoboxes. These programs do work, although they have not yet been very thoroughly tested. They simply need to go through the 3 test process.

2017-11-28 03:51 UTC, jschool504 requested changes

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B1.java
> +    //RelicRecoveryVuMark vuMark;
#Fix Remove all the unused Vuforia code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B1.java
> +        //relicTemplate.setName("relicVuMarkTemplate");
#Fix remove 69-77

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B1.java
> +        //relicTrackables.activate();
#Fix remove

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B1.java
> +            //telemetry.update();
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B1.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +    //RelicRecoveryVuMark vuMark;
#Fix remove commented code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +        //relicTemplate.setName("relicVuMarkTemplate");
#Fix remove lines 72-80

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +        //relicTrackables.activate();
#Fix remove

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +            //telemetry.update();
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Blue/Auto_B2.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +    //RelicRecoveryVuMark vuMark;
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +        //relicTemplate.setName("relicVuMarkTemplate");
#Fix remove commented out code 73-81

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +        //relicTrackables.activate();
#Fix remove

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +            //telemetry.update();
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R1.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R2.java
> +    //RelicRecoveryVuMark vuMark;
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R2.java
> +        //relicTemplate.setName("relicVuMarkTemplate");
#Fix remove lines 73-81

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R2.java
> +            //telemetry.update();
#Fix commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R2.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/Red/Auto_R2.java
> +                    } break;*/
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Robot/SubSystems/BlockLift.java
> +//            }
#Fix remove commented out code

2017-11-28 03:51 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Robot/SubSystems/BlockLift.java
> +//            }
#Fix remove commented out code

2017-11-28 03:55 UTC, jschool504 commented
#FYI @amoller655 @Andor16 We should look at moving the case definitions into a common file and trying to collect case implementations into a common file so that individual autonomous programs can be slimmed down to defining what cases are executed in what order for a given autonomous program.

2017-11-30 01:00 UTC, amoller655 approved these changes
I'm fine with all of these changes and I don't see any problems other than what Jeremy has addressed. Thanks for streamlining my code as well!

2017-11-30 01:04 UTC, amoller655 commented
Not to say that Jeremy's issues don't need to be fixed, it's just that I don't see anything other than that that that needs to be fixed

2017-12-31 21:05 UTC, jschool504 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/GMR/Autonomous/States.java
> +    DRIVEBACK2,
#fix We need a more descriptive name for this state.

2017-12-31 21:10 UTC, jschool504 approved these changes

2017-12-31 21:11 UTC, jschool504 commented
LGTM after last comment fixed 👍

2017-12-31 21:12 UTC, merged